### ISSUE TITLE
Microfeatures link is broken

### ISSUE THREAD

**Issue by BasThomas** [pepibumur/pepibumur.github.io#1]
Seems to reference to an incomplete URL; see [here](https://github.com/pepibumur/pepibumur.github.io/blob/master/_data/navigation.yml#L3-L4).

**Comment by pepibumur** [comment]
Thanks for reporting it! Let me fix it.

**Comment by pepibumur** [comment]
Fixed https://github.com/pepibumur/pepibumur.github.io/commit/07ff6d5778ef1e713caf8b2908983af87fa9681a
